catenax-ng/tx-portal-cd

charts/portal/templates/deployment-frontend-portal.yaml
charts/portal/templates/deployment-frontend-registration.yaml
charts/portal/values-beta.yaml
charts/portal/values-dev.yaml
charts/portal/values-int.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml
charts/portal/values.yaml

https://jira.catena-x.net/browse/CPLP-1874

enabler: cplp-1874 add env specfic config in frontend containers

---

charts/portal/values-beta.yaml
charts/portal/values-dev.yaml
charts/portal/values-int.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml

to successfully authenticate for the clearinghouse call, the url got adjusted
Refs: CPLP-1985

feat(clearinghouse): Adjust clearinghouse base address and token address

---

charts/portal/templates/cronjob-backend-checklist.yaml
charts/portal/values.yaml

to enable the removal of specific roles for a clients when activating the application a new configuration value is set for the checklist worker
Refs: CPLP-1783

feat(checklist): Add clientToRemoveRolesOnActivation config

---

charts/portal/values-beta.yaml

fix(sd-factory): Adjust the sd-factory base address for beta

---

charts/portal/values-beta.yaml
charts/portal/values-dev.yaml
charts/portal/values-int.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml

fix(clearinghouse): adjust clearinghouse auth url

---

charts/portal/templates/deployment-backend-appmarketplace.yaml
charts/portal/values.yaml

added new document type-CONFORMITY_APPROVAL_BUSINESS_APPS to delete an app document
Refs: CPLP-2244

feat(appReleaseProcess): delete app document 

---

CHANGELOG.md
README.md
argocd-portal/appsetup-beta.yaml
argocd-portal/appsetup-int.yaml
argocd-portal/appsetup-pen.yaml
argocd-portal/appsetup-preprod.yaml
charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/values-beta.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml
charts/portal/values.yaml

release(1.1.0): execute release steps

---

charts/portal/templates/deployment-frontend-portal.yaml
charts/portal/templates/deployment-frontend-registration.yaml

Joint PR across repos:
https://github.com/catenax-ng/tx-portal-cd/pull/43
https://github.com/catenax-ng/tx-portal-assets/pull/108
https://github.com/catenax-ng/tx-portal-frontend/pull/248
https://github.com/catenax-ng/tx-portal-frontend-registration/pull/98

feature / run all frontend components local

---

charts/portal/templates/cronjob-backend-checklist.yaml
charts/portal/values.yaml

* add lock to process-entity with expiring-time
Refs: CPLP-2348

feature(checklist-worker): process-concurrency

---

charts/portal/templates/deployment-backend-administration.yaml
charts/portal/values.yaml

added new endpoint to fetch frame document of CX_FRAME_CONTRACT document type
Refs: CPLP-2342

feat(administration/document): get frame document

---

charts/portal/templates/deployment-backend-registration.yaml
charts/portal/values.yaml

added new endpoint to get registration document of CX_FRAME_CONTRACT documenttypeid
Refs: CPLP-2341

feat(registration): get registration document document typeid

---

charts/portal/templates/deployment-backend-administration.yaml

fix configuration value for Document__FRAMEDOCUMENTTYPEIDS__0
Refs: CPLP-2342

fix(administration): fix config value

---

CHANGELOG.md
README.md
argocd-portal/appsetup-beta.yaml
argocd-portal/appsetup-int.yaml
argocd-portal/appsetup-pen.yaml
argocd-portal/appsetup-preprod.yaml
charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/values-beta.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml
charts/portal/values.yaml

release(1.2.0): merge release into helm-environments

---

.github/workflows/portal-assets-rc-image-update.yml
.github/workflows/portal-assets-release-image-update.yml
.github/workflows/portal-backend-rc-image-update.yml
.github/workflows/portal-backend-release-image-update.yml
.github/workflows/portal-chart-test.yaml
.github/workflows/portal-rc-image-update.yml
.github/workflows/portal-registration-rc-image-update.yml
.github/workflows/portal-registration-release-image-update.yml
.github/workflows/portal-release-image-update.yml

chore(workflows): update main

---

README.md
charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/values.yaml

release(1.3.0-RC2): add helm-environments updates

---

charts/portal/templates/deployment-backend-services.yaml
charts/portal/values.yaml

feat(service): adding config variable for deleteDocumentTypeIds
Backend PR : https://github.com/catenax-ng/tx-portal-backend/pull/318
Ref: CPLP-2493

feat(service): adding config variable for deleteDocumentTypeIds

---

CHANGELOG.md
README.md
charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/values.yaml

release(1.3.0-RC3): add updates from release candidate

---

charts/portal/templates/deployment-backend-services.yaml
charts/portal/values.yaml

Refs: CPLP-2429
Depending Backend [PR](https://github.com/catenax-ng/tx-portal-backend/pull/308)

feat(serviceAccount): add config value for serviceAccount Profiles

---

charts/portal/templates/deployment-backend-services.yaml
charts/portal/values.yaml

Ref: CPLP-2493
https://github.com/catenax-ng/tx-portal-backend/pull/336

feat(service): adding config variable for deleteDocumentTypeIds (#63)

---

CHANGELOG.md
README.md
charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/README.md.gotmpl
charts/portal/templates/deployment-backend-services.yaml
charts/portal/templates/secret-backend-external-db.yaml
charts/portal/templates/secret-backend-interfaces.yaml
charts/portal/templates/secret-backend-keycloak.yaml
charts/portal/templates/secret-backend-mailing.yaml
charts/portal/templates/secret-backend-postgres-init.yaml
charts/portal/values.yaml

release(1.3.0-RC4): add updates from release candidate

---

.github/workflows/processes-worker-image-update.yml

due to renaming of checklist worker to processes worker
relates to https://github.com/catenax-ng/tx-portal-cd/pull/48

chore: update image update workflow

---

CHANGELOG.md
README.md
argocd-portal/appsetup-beta.yaml
argocd-portal/appsetup-int.yaml
argocd-portal/appsetup-pen.yaml
argocd-portal/appsetup-preprod.yaml
charts/portal/Chart.yaml
charts/portal/README.md

release(1.4.0-alpha): merge release into helm-environments

---

charts/portal/templates/deployment-backend-administration.yaml
charts/portal/values.yaml

corresponding backend PR: https://github.com/catenax-ng/tx-portal-backend/pull/355
Refs: CPLP-1801

cleanup unused config

---

charts/portal/templates/deployment-backend-administration.yaml
charts/portal/templates/deployment-backend-appmarketplace.yaml
charts/portal/templates/deployment-backend-notification.yaml
charts/portal/templates/deployment-backend-provisioning.yaml
charts/portal/templates/deployment-backend-registration.yaml
charts/portal/templates/deployment-backend-services.yaml
charts/portal/values-beta.yaml
charts/portal/values-dev.yaml
charts/portal/values-int.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml
charts/portal/values-rc.yaml
charts/portal/values.yaml

corresponding backend-PR: https://github.com/catenax-ng/tx-portal-backend/pull/358

fix(error on initialization): add healthcheck-probes to backend-services

---

charts/portal/values-beta.yaml
charts/portal/values-dev.yaml
charts/portal/values-int.yaml
charts/portal/values-pen.yaml
charts/portal/values-preprod.yaml
charts/portal/values-rc.yaml

bugfix(provisioniongservice) fix incorrect healthcheck configuration

---

CHANGELOG.md
README.md
charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/README.md.gotmpl
charts/portal/values.yaml

release(1.3.0): add updates from rc4

---

charts/portal/templates/deployment-backend-appmarketplace.yaml
charts/portal/values.yaml

corresponding Backend-PR: https://github.com/catenax-ng/tx-portal-backend/pull/360
Refs: CPLP-2360

feat(app): add technical user profil to config

---

charts/portal/templates/deployment-backend-appmarketplace.yaml
charts/portal/templates/deployment-backend-services.yaml
charts/portal/values.yaml

Refs: CPLP-2521
corresponding Backend-PR: [369](https://github.com/catenax-ng/tx-portal-backend/pull/369)

feat(offer): add companyAdminRoles to service & app
